services:
  postgres_database:
    image: 'postgres:latest'
    container_name: 'PostgresCont'
    env_file: '.env'
    environment:
      - 'POSTGRES_PASSWORD=qwerty'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=local_database'
    ports:
      - '5432:5432'
