ALTER TABLE PUBLIC.EXERCISE ADD COLUMN WEIGHTS smallint;
ALTER TABLE PUBLIC.EXERCISE
ADD CONSTRAINT weights_positive_under_300 check ((WEIGHTS >= 0)
    AND (WEIGHTS <= 300));
UPDATE PUBLIC.EXERCISE
SET WEIGHTS = 0;